//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTA2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public System.Guid ID { get; set; }
        public string NameCN { get; set; }
        public string NameEN { get; set; }
        public string ImgUrl { get; set; }
        public string Type { get; set; }
    }
}
